application_name:                MyApp
stream_name:                     samplestream
kinesis_endpoint:                https://kinesis.us-east-1.amazonaws.com
aws_access_key_id:               AKIAIIBTDJRZNRVZNTUA
aws_secret_key:                  07tCPBFE70B98RqLRXnw/hd2L012N07//xrlJw9a
max_records:                     1
task_backoff_interval_millis:    1000
